
# this file is automatically generated by configure.sh
 
BUILD_DIR=/home/imagebuilder/projects/os_dev/build
BOCHS_DIR=/home/imagebuilder/projects/os_dev/os/emulators/bochs
ROOTFS_DIR=/home/imagebuilder/projects/os_dev/build/rootfs/
