#!/bin/bash

if [[ -e configure.mk ]] ; then
    mv configs.mk configs.mk.bk
fi

echo "" > configs.mk
echo "# this file is automatically generated by configure.sh" >> configs.mk
echo " " >> configs.mk

if [[ "x$BUILD_DIR" == "x" ]] ; then
    BUILD_DIR=$(cd ../build/; pwd)
fi

if [[ "x$BOCHS_DIR" == "x" ]] ; then
    BOCHS_DIR=$(cd ./emulators/bochs/; pwd)
fi

if [[ "x$ROOTFS_DIR" == "x" ]] ; then
    ROOTFS_DIR=$BUILD_DIR/rootfs/
fi

echo "Setting up BUILD_DIR: $BUILD_DIR"
echo "BUILD_DIR=$BUILD_DIR" >> configs.mk

echo "Setting up BOCHS_DIR: $BOCHS_DIR"
echo "BOCHS_DIR=$BOCHS_DIR" >> configs.mk

echo "Setting up ROOTFS_DIR: $ROOTFS_DIR"
echo "ROOTFS_DIR=$ROOTFS_DIR" >> configs.mk

echo "Done."

exit 0
